### PR TITLE
pin babel/core version to 7.0.0

### LINKED ISSUE #9: Broken CD build results in outdated api.stackstorm.com
This repository is responsible for generating https://api.stackstorm.com/ for stable st2 version and https://api-unstable.stackstorm.com/  for st2 `master` based on StackStorm/st2 Swagger spec.

Example build: https://circleci.com/gh/StackStorm/st2apidocs/516
Failure happens in "Generate API Documentation" step:
```
#!/bin/bash -eo pipefail
if [[ "${ST2_BRANCH}" =~ ^v[0-9]+\.[0-9]+$ ]]; then
  st2apidocgen --render --output
elif [ "${ST2_BRANCH}" == "master" ]; then
  st2apidocgen --render --output
else
  st2apidocgen --render /${CIRCLE_BUILD_NUM} --output
fi

(node:195) UnhandledPromiseRejectionWarning: Error: Cannot find module '@babel/core'
 babelify@10 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babelify@8'.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/st2apidocgen/node_modules/babelify/index.js:9:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:195) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

which is related to Javascript dependencies for this repository.

The regression happened in https://github.com/StackStorm/st2apidocs/pull/7 and https://github.com/StackStorm/st2apidocgen/pull/6

Ideally to fix the regression and update Javascript dependencies for this repo to still function properly.

### PR DESCRIPTION
**Pull request by Sheshagiri**
this should fix the following error 
```
#!/bin/bash -eo pipefail
if [[ "${ST2_BRANCH}" =~ ^v[0-9]+\.[0-9]+$ ]]; then
  st2apidocgen --render --output
elif [ "${ST2_BRANCH}" == "master" ]; then
  st2apidocgen --render --output
else
  st2apidocgen --render /${CIRCLE_BUILD_NUM} --output
fi

(node:195) UnhandledPromiseRejectionWarning: Error: Cannot find module '@babel/core'
 babelify@10 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babelify@8'.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/st2apidocgen/node_modules/babelify/index.js:9:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
(node:195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:195) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
which is described in https://github.com/StackStorm/st2apidocs/issues/9

fixes: https://github.com/StackStorm/st2apidocs/issues/9

### CODE REVIEW

**Comment by arm4b** [comment]
I also updated CircleCI settings here so it starts showing the build status for forked PRs.

**Comment by Sheshagiri** [comment]
@armab this is now ready for review. verified the changes made here in the following build https://app.circleci.com/pipelines/github/StackStorm/st2apidocs/39/workflows/23457cb5-56b8-46d0-b257-5fcdafbf24a8/jobs/554

**Review by arm4b — APPROVED** [review]
:+1:
